<?php defined('ABSPATH') || exit; ?>
<div class="wrap esp-admin"><h1><?php esc_html_e('Student Promotion','exam-system-pro'); ?></h1>
<p class="description"><?php esc_html_e('Promote a student from the active Campus/Session to a new class and session.','exam-system-pro'); ?></p>
<?php if (sanitize_key($_GET['esp_status']??'')==='updated'): ?><div class="notice notice-success"><p><?php esc_html_e('Student promoted successfully.','exam-system-pro'); ?></p></div><?php elseif (sanitize_key($_GET['esp_status']??'')==='error'): ?><div class="notice notice-error"><p><?php echo esc_html(sanitize_text_field(wp_unslash($_GET['esp_error']??__('Promotion failed.','exam-system-pro')))); ?></p></div><?php endif; ?>
<form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" class="esp-card esp-record-form"><input type="hidden" name="action" value="esp_promote_student"><?php wp_nonce_field('esp_admin_record'); ?>
<p><label for="esp-promotion-student"><strong><?php esc_html_e('Student','exam-system-pro'); ?></strong></label><br><select id="esp-promotion-student" name="student_id" required><option value=""><?php esc_html_e('Select student','exam-system-pro'); ?></option><?php foreach($students as $student): ?><option value="<?php echo esc_attr($student['id']); ?>"><?php echo esc_html(trim(($student['roll_no']??'').' - '.($student['student_name']??'').' ('.($student['class_name']??'').')')); ?></option><?php endforeach; ?></select></p>
<p><label for="esp-promotion-class"><strong><?php esc_html_e('New class','exam-system-pro'); ?></strong></label><br><select id="esp-promotion-class" name="new_class_id" required><option value=""><?php esc_html_e('Select class','exam-system-pro'); ?></option><?php foreach($classes as $class): ?><option value="<?php echo esc_attr($class['id']); ?>"><?php echo esc_html($class['class_name']); ?></option><?php endforeach; ?></select></p>
<p><label for="esp-promotion-session"><strong><?php esc_html_e('New session','exam-system-pro'); ?></strong></label><br><select id="esp-promotion-session" name="new_session_id" required><option value=""><?php esc_html_e('Select session','exam-system-pro'); ?></option><?php foreach($sessions as $row): ?><option value="<?php echo esc_attr($row['id']); ?>"><?php echo esc_html($row['session_name']); ?></option><?php endforeach; ?></select></p>
<?php submit_button(__('Promote student','exam-system-pro'),'primary'); ?></form>
<div class="esp-saved-records"><h2><?php esc_html_e('Students in active session','exam-system-pro'); ?> <span class="esp-record-count"><?php echo esc_html(count($students)); ?></span></h2><table class="widefat striped esp-admin-table"><thead><tr><th><?php esc_html_e('Roll','exam-system-pro'); ?></th><th><?php esc_html_e('Student','exam-system-pro'); ?></th><th><?php esc_html_e('Current class','exam-system-pro'); ?></th></tr></thead><tbody><?php foreach($students as $student): ?><tr><td><?php echo esc_html($student['roll_no']); ?></td><td><?php echo esc_html($student['student_name']); ?></td><td><?php echo esc_html($student['class_name']); ?></td></tr><?php endforeach; ?><?php if(!$students): ?><tr><td colspan="3"><?php esc_html_e('No students found.','exam-system-pro'); ?></td></tr><?php endif; ?></tbody></table></div></div>
